src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Wallet::class, mappedBy="account", orphanRemoval=true)
     */
    private $wallet;

    public function __construct()
    {
        $this->wallet = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Wallet>
     */
    public function getWallet(): Collection
    {
        return $this->wallet;
    }

    public function addWallet(Wallet $wallet): self
    {
        if (!$this->wallet->contains($wallet)) {
            $this->wallet[] = $wallet;
            $wallet->setAccount($this);
        }

        return $this;
    }

    public function removeWallet(Wallet $wallet): self
    {
        if ($this->wallet->removeElement($wallet)) {
            // set the owning side to null (unless already changed)
            if ($wallet->getAccount() === $this) {
                $wallet->setAccount(null);
            }
        }

        return $this;
    }
}

templates/main/account.html.twig
{% extends 'base.html.twig' %}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/account.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'account')}}">
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('form') }}
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'account')}}{% endblock %}

{% block body %}
	<div class="container mt-5">
		<h3 class="text-white">{{ 'email'|trans({}, 'account')}} : {{ app.user.username }}</h3>

		{% for flash_success in app.flashes('flash_success') %}
			<div class="alert alert-success my-2" role="success">{{ flash_success }}</div>
		{% endfor %}
		{% for flash_error in app.flashes('flash_error') %}
			<div class="alert alert-danger my-2" role="error">{{ flash_error }}</div>
		{% endfor %}

		{{ form_start(formEditPW, {'attr' : {'id':'registerForm', 'class' : 'customForm'}}) }}
			<h3 class="text-white mt-3">{{ 'editPassword.title'|trans({}, 'account')}}</h1>
			{{ form_row(formEditPW.old_password) }}
			{{ form_row(formEditPW.new_password) }}
			{{ form_row(formEditPW.save) }}
		{{ form_end(formEditPW) }}
		{{ form_start(formDeleteAccount) }}
			{{ form_row(formDeleteAccount.submit, {'label' : 'delete'|trans({}, 'account'), 'attr' : {'class' : 'btn btn-danger'}})}}
		{{ form_end(formDeleteAccount)}}
		
	</div>
{% endblock %}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/contact.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'contact')}}">
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('contact') }}
{% endblock %}

{% block title %}Contact{% endblock %}

{% block body %}
	<script>
		function onSubmit(token) {
			document.getElementById("contactForm").submit();
		}
	</script>
	<div class="container text-dark mt-5">
		{{ form_start(form, {'attr' : {'id' : 'contactForm'}}) }}
			{% for flash_success in app.flashes('flash_success') %}
				<div class="alert alert-success my-2" role="success">{{ flash_success }}</div>
			{% endfor %}
			<h3 class="mb-2 text-white text-center">{{ 'titleForm'|trans({}, 'contact')}}</h3>
			{{ form_row(form.email) }}
			{{ form_row(form.message) }}
			{{ form_row(form.send) }}
		{{ form_end(form) }}
	</div>
{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/home.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'home')}}">
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('home') }}
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'home')}}{% endblock %}

{% block body %}
	<div class="container-fluid">
		<h1 class="text-white text-center pt-5">{{ 'welcomeMessage'|trans({}, 'home')}} Crypto Wallet Monitoring !</h1>

		<div class="container d-flex justify-content-center text-center">
			<p class="display-6 fs-2 mt-4">{{ 'description'|trans({}, 'home')}}</p>
		</div>
		
		<div class="container mt-5 mb-5 d-flex justify-content-center">
			<div class="row">
				<div class="col d-flex justify-content-center">
					<img class="imageSize img-fluid" src="{{asset('images/icons/logo-Binance.png')}}" alt="Binance-logo">
				</div>
				<div class="col d-flex justify-content-center">
					<img class="imageSize img-fluid" src="{{asset('images/icons/logo-Coinbase.png')}}" alt="Coinbase-logo">
				</div>
				<div class="col d-flex justify-content-center">
					<img class="imageSize img-fluid" src="{{asset('images/icons/logo-FTX.png')}}" alt="FTX-logo">
				</div>
				<div class="col d-flex justify-content-center">
					<img class="imageSize img-fluid" src="{{asset('images/icons/logo-Kucoin.png')}}" alt="Kucoin-logo">
				</div>
				<div class="col d-flex justify-content-center">
					<img class="imageSize img-fluid" src="{{asset('images/icons/logo-Gate.io.png')}}" alt="Gate_io-logo">
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/main/login.html.twig
{% extends 'base.html.twig' %}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/login.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'login')}}">
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('form') }}
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'login')}}{% endblock %}

{% block body %}
	{# Captcha submit #}
	<script>
		function onSubmit(token) {
			document.getElementById("loginForm").submit();
		}
	</script>
	<div class="container mt-5">
		<form method="post" class="customForm" id="loginForm">
			{% if error %}
				<div class="alert alert-danger mb-2">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
			{% endif %}

			<h3 class="mb-3 text-white">{{ 'formTitle'|trans({}, 'login')|raw}}</h1>

			<div class="form-floating text-dark mb-2">
				<input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control customInput" 
					autocomplete="email" placeholder="{{ 'emailInput'|trans({}, 'login')}}" required>
				<label for="inputEmail">{{ 'emailInput'|trans({}, 'login')}}</label>
			</div>

			<div class="form-floating text-dark mb-2">
				<input type="password" name="password" id="inputPassword" class="form-control customInput" 
					autocomplete="current-password" placeholder="{{ 'passwordInput'|trans({}, 'login')}}" required>
				<label for="inputPassword">{{ 'passwordInput'|trans({}, 'login')}}</label>
			</div>

			<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
	
			<button class="g-recaptcha w-100 btn btn-lg btn-warning mb-2" data-sitekey="{{ app.request.server.get('GOOGLE_RECAPTCHAv3_SITE_KEY') }}"
				data-callback='onSubmit' data-action='submit'>
				{{ 'submitButton'|trans({}, 'login')}}
			</button>
		</form>
		<a href="/reset-password" class="link-primary">{{ 'forgotPassword'|trans({}, 'login')}}</a>
	</div>
{% endblock %}

templates/main/privacyPolicy.html.twig
{% extends 'base.html.twig' %}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/privacy.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'privacyPolicy') }}">
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'privacyPolicy') }}{% endblock %}

{% block body %}
	<div class="container text-white mt-5">
                <h3 class="mb-2 text-center">{{ 'body.title'|trans({}, 'privacyPolicy') }}</h3>
                {{ 'body.p'|trans({}, 'privacyPolicy')|raw }}
	</div>
{% endblock %}

templates/main/question.html.twig
{% extends 'base.html.twig'%}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/question.png')}}" type="image/x-icon">
	<meta name="description" content="{{ 'meta'|trans({}, 'question') }}">
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('question') }}
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'question') }}{% endblock %}
{% block body %}
	{# Questions #}
	<div class="container mt-5">
		<div>
			<h3>{{ 'question.utility'|trans({}, 'question') }}</h3>
			<p>{{ 'question.answer1'|trans({}, 'question') }}</p>
		</div>
		<div>
			<h3>{{ 'question.works'|trans({}, 'question') }}</h3>
			<p>{{ 'question.answer2'|trans({}, 'question') }}</p>
		</div>
		<div>
			<h3>{{ 'question.protection'|trans({}, 'question') }}</h3>
			<p>{{ 'question.answer3'|trans({}, 'question') }}</p>
		</div>
		<div>
			<h3>{{ 'question.whatPlatform'|trans({}, 'question') }}</h3>
			<p>{{ 'question.answer4'|trans({}, 'question') }}</p>
		</div>
	</div>

	{# Tutorial #}
	<div class="container mt-5 w-100">
		<h3 class="mb-3">{{ 'tutorial.title'|trans({}, 'question') }}</h3>
		<div class="row row-cols-1">
			<div class="col mb-3">
				<fieldset class="border rounded-3 p-3">
					<legend class="h3 text-white float-none w-auto px-3">
						<select class="form-select" id="selectExchange">
							<option value="Binance">Binance</option>
							<option value="Coinbase">Coinbase</option>
							<option value="FTX">FTX</option>
							<option value="Kucoin">Kucoin</option>
							<option value="Gate">Gate</option>
						</select>
					</legend>
					{# Binance tutorial #}
					<div class="row row-cols-1" id="binance">
						<div class="col mb-2">
							<h4>{{ 'tutorial.binance.browser'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/binance/binance1.png')}}" alt="api management">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.binance.mobile'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/binance/binance1-mobile.png')}}" alt="api management mobile">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.binance.create'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/binance/binance2.png')}}" alt="create api">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.binance.management'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/binance/binance3.png')}}" alt="api list">
						</div>
					</div>
					{# Coinbase tutorial #}
					<div class="row row-cols-1" id="coinbase" hidden>
						<h3 class="mb-3">{{ 'tutorial.coinbase.info'|trans({}, 'question') }}</h3>
						<div class="col mb-2">
							<h4>{{ 'tutorial.coinbase.add'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/coinbase/coinbase1.png')}}" alt="add">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.coinbase.login'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/coinbase/coinbase2.png')}}" alt="sign">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.coinbase.authorize'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/coinbase/coinbase3.png')}}" alt="authorize">
						</div>
					</div>
					{# FTX tutorial #}
					<div class="row row-cols-1" id="ftx" hidden>
						<div class="col mb-2">
							<h4>{{ 'tutorial.ftx.where'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/ftx/ftx1.png')}}" alt="where">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.ftx.generate'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/ftx/ftx2.png')}}" alt="generate">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.ftx.exit'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/ftx/ftx3.png')}}" alt="exit">
						</div>
					</div>
					{# Kucoin tutorial #}
					<div class="row row-cols-1" id="kucoin" hidden>
						<div class="col mb-2">
							<h4>{{ 'tutorial.kucoin.create'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/kucoin/kucoin2.png')}}" alt="create">
						</div>
						<div class="col mb-2">
							<img class="img-fluid" src="{{asset('images/tutorial/kucoin/kucoin3.png')}}" alt="create input field">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.kucoin.email'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/kucoin/kucoin4.png')}}" alt="email confirmation">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.kucoin.exit'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/kucoin/kucoin5.png')}}" alt="exit">
						</div>
					</div>
					{# Gate.io tutorial #}
					<div class="row row-cols-1" id="gate" hidden>
						<div class="col mb-2">
							<h4>{{ 'tutorial.gate.where'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/gate/gate1.png')}}" alt="where">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.gate.create'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/gate/gate2.png')}}" alt="api version">
						</div>
						<div class="col mb-2">
							<img class="img-fluid" src="{{asset('images/tutorial/gate/gate3.png')}}" alt="create button">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.gate.input'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/gate/gate4.png')}}" alt="input field">
						</div>
						<div class="col mb-2">
							<h4>{{ 'tutorial.gate.exit'|trans({}, 'question') }}</h4>
							<img class="img-fluid" src="{{asset('images/tutorial/gate/gate5.png')}}" alt="exit">
						</div>
					</div>
				</fieldset>
			</div>
		</div>
	</div>
{% endblock %}

templates/main/sitemap.html.twig
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    {% for url in urls %}
    <url>
        <loc>
            {% if url.loc|replace({hostname:''}) == url.loc %}
                {{ hostname }}{{ url.loc }}
            {% else %}
                {{ url.loc }}
            {% endif %}
        </loc>
        {% if url.lastmod is defined %}
            <lastmod>{{url.lastmod}}</lastmod>
        {% endif %}

        {% if url.changefreq is defined %}
            <changefreq>{{url.changefreq}}</changefreq>
        {% endif %}

        {% if url.priority is defined %}
            <priority>{{url.priority}}</priority>
        {% endif %}
    </url>
    {% endfor %}
</urlset>

templates/main/wallet.html.twig
{% extends 'base.html.twig'%}
{% block head %}
	<link rel="icon" href="{{asset('images/favicons/wallet.png')}}" type="image/x-icon">
    <meta name="description" content="{{ 'meta'|trans({}, 'wallet')}}">
{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('form') }}
	{{ encore_entry_link_tags('wallet_scss') }}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('wallet') }}
{% endblock %}

{% block title %}{{ 'title'|trans({}, 'wallet')}}{% endblock %}

{% block body %}
    {% for flash_success in app.flashes('flash_success') %}
        <div class="alert alert-success my-2" role="success">{{ flash_success }}</div>
    {% endfor %}

    {% for flash_error in app.flashes('flash_error') %}
        <div class="alert alert-danger my-2" role="error">{{ flash_error }}</div>
    {% endfor %}

    {# if user don't have wallet we do not display allwallettotal and update wallet button #}
    {% if data %}
        <div class="container mt-5 text-center">
            {# All wallet total value #}
            <h1 class="text-white">{{ 'total'|trans({}, 'wallet')}}: {{allWalletTotal}}$</h1>
            {# Update all wallet value #}
            <a href="{{ path('updateWalletPrice')}}" class="btn btn-outline-info mt-2 w-100 btn-lg" id="updateButton">
                {{'updateButton'|trans({},'wallet')}}
            </a>
        </div>
    {% endif %}

    <div class="container mt-5">
        {# if screen width > 1200px 3 div are display #}
        <div class="row row-cols-xl-3">
            {# Add wallet div #}
            <div class="col mb-5 text-dark">
                {# Form for adding new wallet #}
                <fieldset class="border rounded-3 p-3 walletCustomFieldset">
                    <legend class="h3 text-white float-none w-auto px-3">
                        {{ 'addWalletForm.formTitle'|trans({},'wallet')|raw}}
                    </legend>
                    {{ form_start(AddWalletForm, {'attr' : {'id':'registerForm', 'class' : 'customForm'}})}}
                        {{ form_row(AddWalletForm.name) }}
                        {{ form_row(AddWalletForm.apiKey) }}
                        {{ form_row(AddWalletForm.secretKey) }}
                        {{ form_row(AddWalletForm.passPhrase) }}
                        {{ form_row(AddWalletForm.save) }}
                    {{ form_end(AddWalletForm) }}
                </fieldset>
                
            </div>

            {# Display all wallet name and data #}
            {% for key, wallets in data %}
                <div class="col mb-5">
                    <fieldset class="border rounded-3 p-3 walletCustomFieldset">
                        {# Wallet name #}
                        <legend class="h3 text-white float-none w-auto px-3">{{wallets['name']}} <img class="customIcon img-fluid" srcset="{{asset('images/icons/logo-' ~ wallets['name'] ~ '.png')}}"></legend>

                        {# Wallet value #}
                        {% if eachWalletTotal[key]['error'] is defined %}
                            <h3 class="text-center mb-4 text-danger">{{eachWalletTotal[key]['error']}}</h3>
                        {% else %}
                            <h3 class="text-center mb-4"><u>Total: {{eachWalletTotal[key]}}$</u></h3>
                            <div class="table-responsive walletCustomTable" id="table{{key}}">
                                <table class="table table-borderless table-sm text-white text-center" id="t{{key}}">
                                    <thead class="h5">
                                        <tr>
                                            <th scope="col">{{ 'eachWallet.symbol'|trans({},'wallet')}}</th>
                                            <th scope="col">{{ 'eachWallet.quantity'|trans({},'wallet')}}</th>
                                            <th scope="col">{{ 'eachWallet.value'|trans({},'wallet')}}</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {# each coin symbol, quantity, value for each wallet #}
                                        {% if data[key]['data']['errors'] is not defined %}
                                            {% for d in data[key]['data'] %}
                                                <tr>
                                                    <td>
                                                        {% if d.symbol is defined %}
                                                            {{d.symbol}}
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if d.quantity is defined %}
                                                            {{d.quantity}}
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if d.value is defined and d.value != 0 %}
                                                            {{d.value}} $
                                                        {% else %}
                                                            {{ 'eachWallet.valueNull'|trans({},'wallet')}}
                                                            <span data-toggle="tooltip" data-placement="top" title="{{ 'eachWallet.valueNullHelp'|trans({},'wallet')}}">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-question-circle" viewBox="0 0 16 16">
                                                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
                                                                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"></path>
                                                                </svg>
                                                            </span>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        {% endif %}
                            <div class="d-flex justify-content-end mt-3">
                                {# Button for removing selected wallet #}
                                <a class="btn btn-danger me-2" href="{{ path('removeWallet', {'id': data[key]['id'] }) }}">
                                    <spanclass="align-middle">{{ 'eachWallet.removeWalletButton'|trans({},'wallet')}}</span>
                                </a>
                                {# Expande button #}
                                <button type="button" class="btn border-white customButton" id="{{key}}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="28" fill="white"
                                        class="bi bi-arrow-bar-left rotateSVG" viewBox="0 0 16 16" id="rotateSVG{{key}}">
                                        <path fill-rule="evenodd"
                                            d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5zM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5z">
                                        </path>
                                    </svg>
                                </button>
                            </div>
                    </fieldset>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}